//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  vehicle: Vehicle;
  vehicleConnection: VehicleConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryVehicleArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryVehicleConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<VehicleFilter>;
};

export type DocumentFilter = {
  vehicle?: InputMaybe<VehicleFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DocumentFilter>;
};

export type DocumentNode = Vehicle;

export type VehicleImages = {
  __typename?: 'VehicleImages';
  label?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
};

export type Vehicle = Node & Document & {
  __typename?: 'Vehicle';
  name: Scalars['String'];
  category?: Maybe<Scalars['String']>;
  price?: Maybe<Scalars['String']>;
  dailyRate?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  images?: Maybe<Array<Maybe<VehicleImages>>>;
  description?: Maybe<Scalars['String']>;
  features?: Maybe<Array<Maybe<Scalars['String']>>>;
  popular?: Maybe<Scalars['Boolean']>;
  year?: Maybe<Scalars['Float']>;
  mileage?: Maybe<Scalars['String']>;
  transmission?: Maybe<Scalars['String']>;
  fuelType?: Maybe<Scalars['String']>;
  type?: Maybe<Scalars['String']>;
  engineSize?: Maybe<Scalars['String']>;
  doors?: Maybe<Scalars['Float']>;
  seats?: Maybe<Scalars['Float']>;
  color?: Maybe<Scalars['String']>;
  condition?: Maybe<Scalars['String']>;
  serviceHistory?: Maybe<Scalars['String']>;
  accidentHistory?: Maybe<Scalars['String']>;
  warranty?: Maybe<Scalars['String']>;
  registrationStatus?: Maybe<Scalars['String']>;
  insuranceStatus?: Maybe<Scalars['String']>;
  whatsappContact?: Maybe<Scalars['String']>;
  status: Scalars['String'];
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type VehicleImagesFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']>;
  lte?: InputMaybe<Scalars['Float']>;
  gte?: InputMaybe<Scalars['Float']>;
  gt?: InputMaybe<Scalars['Float']>;
  eq?: InputMaybe<Scalars['Float']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']>>>;
};

export type VehicleFilter = {
  name?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  dailyRate?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  images?: InputMaybe<VehicleImagesFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  popular?: InputMaybe<BooleanFilter>;
  year?: InputMaybe<NumberFilter>;
  mileage?: InputMaybe<StringFilter>;
  transmission?: InputMaybe<StringFilter>;
  fuelType?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  engineSize?: InputMaybe<StringFilter>;
  doors?: InputMaybe<NumberFilter>;
  seats?: InputMaybe<NumberFilter>;
  color?: InputMaybe<StringFilter>;
  condition?: InputMaybe<StringFilter>;
  serviceHistory?: InputMaybe<StringFilter>;
  accidentHistory?: InputMaybe<StringFilter>;
  warranty?: InputMaybe<StringFilter>;
  registrationStatus?: InputMaybe<StringFilter>;
  insuranceStatus?: InputMaybe<StringFilter>;
  whatsappContact?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
};

export type VehicleConnectionEdges = {
  __typename?: 'VehicleConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Vehicle>;
};

export type VehicleConnection = Connection & {
  __typename?: 'VehicleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<VehicleConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateVehicle: Vehicle;
  createVehicle: Vehicle;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateVehicleArgs = {
  relativePath: Scalars['String'];
  params: VehicleMutation;
};


export type MutationCreateVehicleArgs = {
  relativePath: Scalars['String'];
  params: VehicleMutation;
};

export type DocumentUpdateMutation = {
  vehicle?: InputMaybe<VehicleMutation>;
  relativePath?: InputMaybe<Scalars['String']>;
};

export type DocumentMutation = {
  vehicle?: InputMaybe<VehicleMutation>;
};

export type VehicleImagesMutation = {
  label?: InputMaybe<Scalars['String']>;
  url?: InputMaybe<Scalars['String']>;
};

export type VehicleMutation = {
  name?: InputMaybe<Scalars['String']>;
  category?: InputMaybe<Scalars['String']>;
  price?: InputMaybe<Scalars['String']>;
  dailyRate?: InputMaybe<Scalars['String']>;
  image?: InputMaybe<Scalars['String']>;
  images?: InputMaybe<Array<InputMaybe<VehicleImagesMutation>>>;
  description?: InputMaybe<Scalars['String']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
  popular?: InputMaybe<Scalars['Boolean']>;
  year?: InputMaybe<Scalars['Float']>;
  mileage?: InputMaybe<Scalars['String']>;
  transmission?: InputMaybe<Scalars['String']>;
  fuelType?: InputMaybe<Scalars['String']>;
  type?: InputMaybe<Scalars['String']>;
  engineSize?: InputMaybe<Scalars['String']>;
  doors?: InputMaybe<Scalars['Float']>;
  seats?: InputMaybe<Scalars['Float']>;
  color?: InputMaybe<Scalars['String']>;
  condition?: InputMaybe<Scalars['String']>;
  serviceHistory?: InputMaybe<Scalars['String']>;
  accidentHistory?: InputMaybe<Scalars['String']>;
  warranty?: InputMaybe<Scalars['String']>;
  registrationStatus?: InputMaybe<Scalars['String']>;
  insuranceStatus?: InputMaybe<Scalars['String']>;
  whatsappContact?: InputMaybe<Scalars['String']>;
  status?: InputMaybe<Scalars['String']>;
};

export type VehiclePartsFragment = { __typename?: 'Vehicle', name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, status: string, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null };

export type VehicleQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type VehicleQuery = { __typename?: 'Query', vehicle: { __typename?: 'Vehicle', id: string, name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, status: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null } };

export type VehicleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<VehicleFilter>;
}>;


export type VehicleConnectionQuery = { __typename?: 'Query', vehicleConnection: { __typename?: 'VehicleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VehicleConnectionEdges', cursor: string, node?: { __typename?: 'Vehicle', id: string, name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, status: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export const VehiclePartsFragmentDoc = gql`
    fragment VehicleParts on Vehicle {
  name
  category
  price
  dailyRate
  image
  images {
    __typename
    label
    url
  }
  description
  features
  popular
  year
  mileage
  transmission
  fuelType
  type
  engineSize
  doors
  seats
  color
  condition
  serviceHistory
  accidentHistory
  warranty
  registrationStatus
  insuranceStatus
  whatsappContact
  status
}
    `;
export const VehicleDocument = gql`
    query vehicle($relativePath: String!) {
  vehicle(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VehicleParts
  }
}
    ${VehiclePartsFragmentDoc}`;
export const VehicleConnectionDocument = gql`
    query vehicleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VehicleFilter) {
  vehicleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VehicleParts
      }
    }
  }
}
    ${VehiclePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      vehicle(variables: VehicleQueryVariables, options?: C): Promise<{data: VehicleQuery, variables: VehicleQueryVariables, query: string}> {
        return requester<{data: VehicleQuery, variables: VehicleQueryVariables, query: string}, VehicleQueryVariables>(VehicleDocument, variables, options);
      },
    vehicleConnection(variables?: VehicleConnectionQueryVariables, options?: C): Promise<{data: VehicleConnectionQuery, variables: VehicleConnectionQueryVariables, query: string}> {
        return requester<{data: VehicleConnectionQuery, variables: VehicleConnectionQueryVariables, query: string}, VehicleConnectionQueryVariables>(VehicleConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "https://content.tinajs.io/1.4/content/6e2aac42-bc7d-4839-a465-f44e0140e2ea/github/main", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  