//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  vehicle: Vehicle;
  vehicleConnection: VehicleConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVehicleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVehicleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VehicleFilter>;
};

export type DocumentFilter = {
  vehicle?: InputMaybe<VehicleFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Vehicle | Folder;

export type VehicleImages = {
  __typename?: 'VehicleImages';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Vehicle = Node & Document & {
  __typename?: 'Vehicle';
  name: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  dailyRate?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<VehicleImages>>>;
  description?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  popular?: Maybe<Scalars['Boolean']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  mileage?: Maybe<Scalars['String']['output']>;
  transmission?: Maybe<Scalars['String']['output']>;
  fuelType?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  engineSize?: Maybe<Scalars['String']['output']>;
  doors?: Maybe<Scalars['Float']['output']>;
  seats?: Maybe<Scalars['Float']['output']>;
  color?: Maybe<Scalars['String']['output']>;
  condition?: Maybe<Scalars['String']['output']>;
  serviceHistory?: Maybe<Scalars['String']['output']>;
  accidentHistory?: Maybe<Scalars['String']['output']>;
  warranty?: Maybe<Scalars['String']['output']>;
  registrationStatus?: Maybe<Scalars['String']['output']>;
  insuranceStatus?: Maybe<Scalars['String']['output']>;
  whatsappContact?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type VehicleImagesFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type VehicleFilter = {
  name?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  dailyRate?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  images?: InputMaybe<VehicleImagesFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  popular?: InputMaybe<BooleanFilter>;
  year?: InputMaybe<NumberFilter>;
  mileage?: InputMaybe<StringFilter>;
  transmission?: InputMaybe<StringFilter>;
  fuelType?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  engineSize?: InputMaybe<StringFilter>;
  doors?: InputMaybe<NumberFilter>;
  seats?: InputMaybe<NumberFilter>;
  color?: InputMaybe<StringFilter>;
  condition?: InputMaybe<StringFilter>;
  serviceHistory?: InputMaybe<StringFilter>;
  accidentHistory?: InputMaybe<StringFilter>;
  warranty?: InputMaybe<StringFilter>;
  registrationStatus?: InputMaybe<StringFilter>;
  insuranceStatus?: InputMaybe<StringFilter>;
  whatsappContact?: InputMaybe<StringFilter>;
};

export type VehicleConnectionEdges = {
  __typename?: 'VehicleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Vehicle>;
};

export type VehicleConnection = Connection & {
  __typename?: 'VehicleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VehicleConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateVehicle: Vehicle;
  createVehicle: Vehicle;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateVehicleArgs = {
  relativePath: Scalars['String']['input'];
  params: VehicleMutation;
};


export type MutationCreateVehicleArgs = {
  relativePath: Scalars['String']['input'];
  params: VehicleMutation;
};

export type DocumentUpdateMutation = {
  vehicle?: InputMaybe<VehicleMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  vehicle?: InputMaybe<VehicleMutation>;
};

export type VehicleImagesMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type VehicleMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  dailyRate?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<VehicleImagesMutation>>>;
  description?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  popular?: InputMaybe<Scalars['Boolean']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  mileage?: InputMaybe<Scalars['String']['input']>;
  transmission?: InputMaybe<Scalars['String']['input']>;
  fuelType?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  engineSize?: InputMaybe<Scalars['String']['input']>;
  doors?: InputMaybe<Scalars['Float']['input']>;
  seats?: InputMaybe<Scalars['Float']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  condition?: InputMaybe<Scalars['String']['input']>;
  serviceHistory?: InputMaybe<Scalars['String']['input']>;
  accidentHistory?: InputMaybe<Scalars['String']['input']>;
  warranty?: InputMaybe<Scalars['String']['input']>;
  registrationStatus?: InputMaybe<Scalars['String']['input']>;
  insuranceStatus?: InputMaybe<Scalars['String']['input']>;
  whatsappContact?: InputMaybe<Scalars['String']['input']>;
};

export type VehiclePartsFragment = { __typename: 'Vehicle', name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null };

export type VehicleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VehicleQuery = { __typename?: 'Query', vehicle: { __typename: 'Vehicle', id: string, name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null } };

export type VehicleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VehicleFilter>;
}>;


export type VehicleConnectionQuery = { __typename?: 'Query', vehicleConnection: { __typename?: 'VehicleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VehicleConnectionEdges', cursor: string, node?: { __typename: 'Vehicle', id: string, name: string, category?: string | null, price?: string | null, dailyRate?: string | null, image?: string | null, description?: string | null, features?: Array<string | null> | null, popular?: boolean | null, year?: number | null, mileage?: string | null, transmission?: string | null, fuelType?: string | null, type?: string | null, engineSize?: string | null, doors?: number | null, seats?: number | null, color?: string | null, condition?: string | null, serviceHistory?: string | null, accidentHistory?: string | null, warranty?: string | null, registrationStatus?: string | null, insuranceStatus?: string | null, whatsappContact?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'VehicleImages', label?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export const VehiclePartsFragmentDoc = gql`
    fragment VehicleParts on Vehicle {
  __typename
  name
  category
  price
  dailyRate
  image
  images {
    __typename
    label
    url
  }
  description
  features
  popular
  year
  mileage
  transmission
  fuelType
  type
  engineSize
  doors
  seats
  color
  condition
  serviceHistory
  accidentHistory
  warranty
  registrationStatus
  insuranceStatus
  whatsappContact
}
    `;
export const VehicleDocument = gql`
    query vehicle($relativePath: String!) {
  vehicle(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VehicleParts
  }
}
    ${VehiclePartsFragmentDoc}`;
export const VehicleConnectionDocument = gql`
    query vehicleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VehicleFilter) {
  vehicleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VehicleParts
      }
    }
  }
}
    ${VehiclePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      vehicle(variables: VehicleQueryVariables, options?: C): Promise<{data: VehicleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VehicleQueryVariables, query: string}> {
        return requester<{data: VehicleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VehicleQueryVariables, query: string}, VehicleQueryVariables>(VehicleDocument, variables, options);
      },
    vehicleConnection(variables?: VehicleConnectionQueryVariables, options?: C): Promise<{data: VehicleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VehicleConnectionQueryVariables, query: string}> {
        return requester<{data: VehicleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VehicleConnectionQueryVariables, query: string}, VehicleConnectionQueryVariables>(VehicleConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  